services:
  - type: web
    name: lstm-fastapi-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NEWS_API_KEY
        fromSecret: true # Make sure to set this secret in your Render dashboard 